### ISSUE TITLE
rule based disturbances and transition rules

### ISSUE THREAD

**Issue by smorken** [cat-cfs/libcbm_py#12]
need to create functions to run CBM rule based disturbances.  

main topics/steps:
  - filtering
    - by classifier sets
    - by age
    - by pool values
    - by other state variables (last dist type, time since last disturbance etc.) 
 - sorting
   - randomly
   - by disturbance product
   - by pool values
   - by age or other state variables
 - objective and splitting
   - area: a total area accumulator for stands in order defined by sorting.  If the area target can be satisfied, a split of the final stand in the sequence may occur to exactly satisfy area target.
   - proportion: a fraction of every eligible record will be disturbed, and the remainder left undisturbed 
   - merchantable: a merchantable C to products accumulator.  the merchC to products flux is hardcoded in CBM3 using products generating disturbance matrices.  In libcbm we can likely generalize this somewhat as a parameterized flux (sources and sinks) 
In CBM3. Splitting can occur in a similar way as the area targeting method.

**Comment by smorken** [comment]
filtering well underway [libcbm.model.cbm.rule_based](https://github.com/cat-cfs/libcbm_py/tree/master/libcbm/model/cbm/rule_based)

**Comment by smorken** [comment]
some work on sorting and filtering done [libcbm.model.cbm.rule_target](https://github.com/cat-cfs/libcbm_py/blob/master/libcbm/model/cbm/rule_based/rule_target.py)

**Comment by xapple** [comment]
Are these tickets from 2019 still current?

**Comment by smorken** [comment]
This is completed. All mentioned features in [here](https://github.com/cat-cfs/libcbm_py/tree/master/libcbm/model/cbm/rule_based) with good unit test coverage [here](https://github.com/cat-cfs/libcbm_py/tree/master/test/model/cbm/rule_based).  Model/integration test coverage in seperate testing package: libcbm_model_test
