### ISSUE TITLE
FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

### ISSUE THREAD

**Issue by paulrougieux** [cat-cfs/libcbm_py#27]
This warning appears in many places when running with the latest version of pandas 1.4.
```
libcbm_py/libcbm/model/cbm/rule_based/transition_rule_processor.py:239: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

libcbm_py/libcbm/data_helpers.py:155: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.

libcbm_py/libcbm/model/cbm/rule_based/event_processor.py:124: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
```
The pandas documentation [Deprecated Frame.append and Series.append](https://pandas.pydata.org/docs/dev/whatsnew/v1.4.0.html#deprecated-frame-append-and-series-append) suggest replacing:

    df1.append(df2)

With 
    
    pandas.concat([df1, df2])

There are 60 occurrences of ".append(" in libcbm_py/libcbm. Unfortunately this is not that straightforward to find and replace these with an automated tool because of the change in structure, the two data frames have to be in a list now. Also because other methods such as list.append() look very similar and you obviously only want to replace the dataframe.append methods.

We also need to change this in several places in our code base.

**Comment by paulrougieux** [comment]
[pandas issue 35407](https://github.com/pandas-dev/pandas/issues/35407) explains the rationale for this replacement:

> "I think that we should deprecate Series.append and DataFrame.append. They're making an analogy to list.append, but it's a poor analogy since the behavior isn't (and can't be) in place. The data for the index and values needs to be copied to create the result."

**Comment by smorken** [comment]
fix underway on [this branch](https://github.com/cat-cfs/libcbm_py/tree/maintenance_and_type_refactoring)

**Comment by smorken** [comment]
This is now fixed on the [main](https://github.com/cat-cfs/libcbm_py/commit/96ec5aaddc09b83e73ac5fe8b1717527e9d271ad) branch, since the scope of [maintenance_and_type_refactoring](https://github.com/cat-cfs/libcbm_py/tree/maintenance_and_type_refactoring) is larger than anticipated.
