### ISSUE TITLE
SIT disturbance event last disturbance type id handling issue

### ISSUE THREAD

**Issue by smorken** [cat-cfs/libcbm_py#33]
There is a problem with the handling of last disturbance type id.  

Before running libcbm, each SIT disturbance type id is mapped to an internal numeric disturbance type id.  This is done because the SIT format allows string identifiers for disturbance type.

The issue in the following code is that the raw SIT_EVENTS LastDistTypeID column is compared versus the mapped internal value.  This will only work correctly if the internal values match the SIT disturbance types exactly.

The result is that the last disturbance type filter does not currently operate correctly in some cases, meaning stands will not be correctly flagged as eligible or ineligible for disturbance events in some cases.

```python
def create_last_disturbance_type_filter(sit_data):

    if int(sit_data["LastDistTypeID"]) == -1:
        return ""
    expression = "({state_variable} {operator} {value})".format(
        state_variable="last_disturbance_type",
        operator="==",
        value=int(sit_data["LastDistTypeID"]))
    return expression
```

Code taken from [here](https://github.com/cat-cfs/libcbm_py/blob/86b2f742bfb556260f2fbd4cc4d15d486a28db75/libcbm/model/cbm/rule_based/sit/sit_stand_filter.py#L152)

**Comment by smorken** [comment]
Planned fix is to pass a "SIT_Disturbance_type_ID" to "internal_disturbance_type_id" map to the method creating the disturbance event filter, and prior to constructing the filter, extract the correct internal numeric value from the map. Now underway!

**Comment by paulrougieux** [comment]
> "The issue in the following code is that the raw SIT_EVENTS LastDistTypeID column is compared versus the mapped internal value. This will only work correctly if the internal values match the SIT disturbance types exactly."

Interesting, we still have disturbance ID that do not match the internal ones so we are affected by this issue.
