### ISSUE TITLE
Could dataframe.from_pandas() deal with int conversion to the int32 type required by libcbm_matrix?

### ISSUE THREAD

**Issue by paulrougieux** [cat-cfs/libcbm_py#41]
The default would be int64 but libcbm_matrix expects an int32. Temporary fix is easy with:

          classifiers[key] = classifiers[key].astype("int32")
          cbm_vars.classifiers = dataframe.from_pandas(classifiers)

Could this conversion be handled by `dataframe.from_pandas()`?

See also [eu_cbm_hat issue 53](https://gitlab.com/bioeconomy/eu_cbm/eu_cbm_hat/-/issues/53).

**Comment by smorken** [comment]
>     * Using this  `assign()` method removes the need to call `cbm_vars.classifiers = dataframe.from_pandas(classifiers)` is that correct?
> 

yes that's right
