### ISSUE TITLE
wrong values in composite_flux_indicator_value in cbm_default.db

### ISSUE THREAD

**Issue by pierre-cantegril** [cat-cfs/libcbm_py#54]
Some of the values in the table composite_flux_indicator_value in the cbm_default database are -1 instead of 1. 

This error concerns the following fluxes :  
- TurnoverMerchLitterInput id 13
- TurnoverFolLitterInput id 14
- TurnoverOthLitterInput id 15
- TurnoverCoarseLitterInput id 16
- TurnoverFineLitterInput id 17

and these composite fluxes : 
- Delta Total Ecosystem id 1
- Delta Total Biomass id 2
- Delta Total DOM id 3
- Net Primary Productivity (NPP) id 4
- Net Ecosystem Productivity (NEP) id 5
- Net Biome Productivity (NBP) id 45

**Comment by smorken** [comment]
Thanks for identifying the issue.  Fix pushed [here.](https://github.com/cat-cfs/libcbm_py/commit/1fe938046d2d65ee6e0588cfb93709c1f521e846) I will close issue on next release.
