### ISSUE TITLE
 OperationalError: no such column: land_class.land_type_id_1

### ISSUE THREAD

**Issue by paulrougieux** [cat-cfs/libcbm_py#58]
- The issue appears to be related to a change in the SQLite database structure. 
- See attached input data for our sample ZZ country.  [zz_input_to_libcbm.zip](https://github.com/cat-cfs/libcbm_py/files/12370927/zz_input_to_libcbm.zip)
- The sample AIDB is at https://gitlab.com/bioeconomy/eu_cbm/eu_cbm_aidb/-/tree/main/countries/ZZ?ref_type=heads
- The issue doesn't happen with older versions of the libcbm2 branch before April 2023 (details on the git checkout instructions below)

Stack trace: 

```
---------------------------------------------------------------------------
OperationalError                          Traceback (most recent call last)
<ipython-input-4-f408e9fb20eb> in <cell line: 1>()
----> 1 runner.run(keep_in_ram=True, verbose=True, interrupt_on_error=True)

~/repos/eu_cbm/eu_cbm_hat/eu_cbm_hat/core/runner.py in run(self, keep_in_ram, verbose, interrupt_on_error)
    231         # Run the model #
    232         self.timer.print_elapsed()
--> 233         self.simulation(interrupt_on_error)
    234         self.timer.print_elapsed()
    235         # Save the results to disk #

~/repos/eu_cbm/eu_cbm_hat/eu_cbm_hat/cbm/simulation.py in __call__(self, interrupt_on_error)
     90         """
     91         try:
---> 92             self.run()
     93         except Exception:
     94             message = "Runner '%s' encountered an exception. See log file."

~/repos/eu_cbm/eu_cbm_hat/eu_cbm_hat/cbm/simulation.py in run(self)
    114         # Create a SIT object #
    115         json_path = str(self.runner.paths.json)
--> 116         self.sit = sit_cbm_factory.load_sit(json_path, str(db_path))
    117         # Do some initialization #
    118         init_inv = sit_cbm_factory.initialize_inventory

~/repos/eu_cbm/libcbm_py/libcbm/input/sit/sit_cbm_factory.py in load_sit(config_path, db_path, db_locale_code)
    296         config["import_config"], os.path.dirname(config_path)
    297     )
--> 298     return initialize_sit(sit_data, config, db_path, db_locale_code)
    299
    300

~/repos/eu_cbm/libcbm_py/libcbm/input/sit/sit_cbm_factory.py in initialize_sit(sit_data, config, db_path, db_locale_code)
    259     if not db_path:
    260         db_path = resources.get_cbm_defaults_path()
--> 261     sit_defaults = SITCBMDefaults(
    262         sit_data, db_path, locale_code=db_locale_code
    263     )

~/repos/eu_cbm/libcbm_py/libcbm/input/sit/sit_cbm_defaults.py in __init__(self, sit_data, db_path, locale_code)
     14         self, sit_data: SITData, db_path: str, locale_code: str = "en-CA"
     15     ):
---> 16         super().__init__(db_path, locale_code)
     17         self.db_path = db_path
     18

~/repos/eu_cbm/libcbm_py/libcbm/model/cbm/cbm_defaults_reference.py in __init__(self, sqlite_path, locale_code)
     89         }
     90
---> 91         self.land_class_ref = self.load_data(
     92             sqlite_path, self.land_class_query, locale_param
     93         )

~/repos/eu_cbm/libcbm_py/libcbm/model/cbm/cbm_defaults_reference.py in load_data(self, sqlite_path, query, query_params)
    129         try:
    130             if query_params:
--> 131                 return cursor.execute(query, query_params).fetchall()
    132             else:
    133                 return cursor.execute(query).fetchall()

OperationalError: no such column: land_class.land_type_id_1
```

# No issue when using an old version of the libcbm 2 branch

```
paul@castanea:~/rp/eu_cbm/libcbm_py$ git checkout da864fda
HEAD is now at da864fda Merge branch 'main' into 2.x
```

**Comment by paulrougieux** [comment]
`land_type_id_1` appears to have been introduced in the following commits:

- https://github.com/cat-cfs/libcbm_py/commit/1c315ae95f6520a61f3abcf82363ecae482725b6 " update queries to support land class/land type tokens" (April 2023)
- https://github.com/cat-cfs/libcbm_py/commit/4bf0f40bdd28955fef397e81cba10632620042bc  "add more fields to the land class reference result " (July 2023)

Is there a way to update the database so that it becomes compatible?

**Comment by smorken** [comment]
As you figured out this is due to an update to schema and functionality in `libcbm` and `cbm_defaults`. The changes were added for unfccc land class tracking and handling both in [cbm_defaults](https://github.com/cat-cfs/cbm_defaults) and in libcbm (see commits around April 2023)

Ways around this issue:

* If you have equivalent data in a CBM-CFS3 Archive index database you can update to the latest version of `cbm_defaults` and re-export the data to have a libcbm@2.x compatible `cbm_defaults` schema
* Otherwise use the newly added [db update](https://github.com/cat-cfs/cbm_defaults/pull/3) routine in the cbm_defaults package.  See [cbm_defaults readme](https://github.com/cat-cfs/cbm_defaults#migrating-database-version) for example usage.

**Comment by paulrougieux** [comment]
Thanks a lot for the update script. We can't use the first option since our libcbm version of the AIDB has diverged from the CBM-CFS3 AIDB. After an updated of  `libcbm_py` and `cbm_defaults`, using the `2x` branch in both repos, I managed to update the AIDB to a version compatible with V2 and to run the model.

The conversion script for our AIDB structure is at https://gitlab.com/bioeconomy/eu_cbm/eu_cbm_hat/-/blob/libcbm2/scripts/conversion/update_aidb_1x_to_2x.py?ref_type=heads
